### ISSUE TITLE
usage sample

### ISSUE THREAD

**Issue by berchik** [NativeScript/worker-loader#1]
Would it be possible to add a basic NS+Angular demo?

Thanks.

**Comment by sis0k0** [comment]
@berchik, the NativeScriptWorkerPlugin and the corresponding loader are still experimental and that's why they are not distributed with npm. We'll consider the idea of adding demo apps once the package is published. Thanks for the feedback!

**Comment by berchik** [comment]
Thanks Stanimira. I’ve managed to work the example and adjust it to my project. It works well with Webpack + worker using tns-android 3.2.0-2017-8-22-1.
Please continue the good work it is a lifesaver!
