### ISSUE TITLE
[request] demo-app using typescript + angular

### ISSUE THREAD

**Issue by echap** [NativeScript/worker-loader#3]
Hi there, 

I'm using ww for a while and this is very important for us to keep them in use, but our setup is with typescript and angular, and so for I haven't ever been able to build with a typescripted web worker. Could you, just as you have the demo app with vanilla {N} have one with the nativescript angular with typescripted  workers ?

Thanks a lot !!

**Comment by Ablankzin** [comment]
I didn't understand. The demo is using NaN, my project is made with it and it was based on this demo.

**Comment by echap** [comment]
My bad, I was checking this one you refers on the readyme : https://github.com/NativeScript/demo-workers

It's fine for me on this demo :)
