### ISSUE TITLE
Error in worker.service : no default export or cannot use 'new' 

### ISSUE THREAD

**Issue by pacome2017** [NativeScript/worker-loader#32]
I use a few workers in my project, I added webpack bundling recently and used the demo-angular in this project to check for the needed changes on workers.
I'm blocked on this one : 
in my worker.service.ts, when I try to import a worker like this 
`import * as SearchWorker from './search.worker';`
then I get an error at 
`const worker = new SearchWorker();` 
`error TS2351: Cannot use 'new'
with an expression whose type lacks a call or construct signature.`

Or if I try to default import without * 
`import ConfigWorker from './config.worker';`
then I get an error 
`error TS1192: Module "..." has no default export `

anything on this ?

**Comment by fhackenb** [comment]
@pacome2017 what was the solution?

**Comment by pacome2017** [comment]
I'm not sure but I think I was missing the `custom.d.ts` file. Then paths should be : 
`import * as WorkerScript from "nativescript-worker-loader!./worker-script";`

I say I'm not sure because I ended up redoing my workers following this : https://github.com/NativeScript/worker-loader#web-workers-withwithout-webpack
